services:

  db:
    image: postgres:15.2-alpine
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:delegated
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: ior2023
      POSTGRES_DB: python
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '.5'
          memory: 512M
    networks:
      - python-network
    restart: unless-stopped
  pgbouncer:
    image: bitnami/pgbouncer
    container_name: pgbouncer
    environment:
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PASSWORD=ior2023
      - POSTGRESQL_DATABASE=python
      - PGBOUNCER_AUTH_TYPE=trust
      - PGBOUNCER_USERLIST_FILE=/bitnami/userlist.txt
      - PGBOUNCER_DSN_0=python=host=db port=5432 dbname=python
    volumes:
      - ./userlist.txt:/bitnami/userlist.txt
    ports:
      - 6432:6432
    networks:
      - python-network
    depends_on:
      - db
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '9080:8080'
    networks:
      - python-network
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass '${REDIS_PASSWORD}'
    volumes:
      - ./cache-redis:/data
    networks:
      - python-network
    env_file:
      - .env

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - BUILD_TYPE=docker # docker | prod | dev
  #   container_name: app
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - PY_ENV=dev # dev | prod
  #   depends_on:
  #     - db
  #     - pgbouncer
  #     - redis
  #   restart: unless-stopped
  #   networks:
  #     - python-network

networks:
  python-network:
    name: python-network
    driver: bridge
